### ISSUE TITLE
Method parameters vs Id data types

### ISSUE THREAD

**Issue by s3YwCf2ZbfJG4SHAfjQMAjtsf** [christianz/printnode-net#7]
Hello,

The library works well, but I just encountered a minor issue between PrintNodePrinter Id type and PrintNodePrintJob static methods.

PrintNodePrinter: Id is a long
PrintNodePrintJob: Id is a long?

The static methods (GetAsync and ListForPrinterAsync) in the PrintNodePrintJob have int parameters.

Peter D

**Comment by christianz** [comment]
Hi Peter, and thanks for your interest in this project. I agree that we should be consistent with the data type for the Id field. The Id field in the PrintNodePrintJob is a special case because its value is only filled in after the print job has been sent to PrintNode.

Fixed by #8 

Edit: Published version 1.1.1 of the Nuget package with this fix included
